[[redirects]]
  from = "/book"
  to = "https://skillest.com/@scottypro/bookings"
  status = 302
  force = true

[[redirects]]
  from = "https://www.yourgolf.com.au/*"
  to = "https://yourgolf.com.au/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/coaching"
  to = "/"
  status = 301
  force = true

[[redirects]]
  from = "/coaching.html"
  to = "/"
  status = 301
  force = true
